require 'staple/buttons_generator'
require 'staple/forms_generator'
require 'staple/colors_generator'
require 'staple/typography_generator'
require 'staple/tables_generator'
require 'staple/theme_generator'
require 'staple/install_generator'
require 'staple/reset_generator'