require 'staple/import_generator'
require 'staple/append_generator'
require 'staple/remove_generator'
require 'staple/amputate_generator'
require 'staple/theme_generator'
require 'staple/install_generator'
